name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Denis kiragu- Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Denis kiragu- Set up Android SDK path for Linux environment
      - name: Configure Android SDK path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/android/local.properties

      # Denis kiragu- Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      # Denis kiragu- Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Denis kiragu- Run linting
      - name: Lint code
        run: flutter analyze

      # Denis kiragu- Run tests
      - name: Run integration tests
        run: flutter test integration_test/ --no-pub

      # Denis kiragu- Clean the build to clear cached paths
      - name: Clean Flutter build
        run: flutter clean

      # Denis kiragu- Build the APK for Android
      - name: Build APK (Android)
        run: flutter build apk

#  Denis kiragu-
#      - name: Build App (iOS)
#        run: flutter build ios --no-sound-null-safety
#        if: runner.os == 'macOS'
