name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Android SDK path for Linux environment
      - name: Configure Android SDK path
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/android/local.properties

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      # Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run linting
      - name: Lint code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Clean the build to clear cached paths
      - name: Clean Flutter build
        run: flutter clean

      # Build the APK for Android
      - name: Build APK (Android)
        run: flutter build apk


#      - name: Build App (iOS)
#        run: flutter build ios --no-sound-null-safety
#        if: runner.os == 'macOS'
